language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
env:
    - STYLE=1
    # keep this list in sync with what's in tox.ini
    - PYMONGO=pymongo30
    - PYMONGO=pymongo31
    - PYMONGO=pymongo32
    - PYMONGO=pymongo33
    - PYMONGO=pymongo34
    - PYMONGO=pymongo35
    - PYMONGO=pymongo36
    - PYMONGO=pymongo37
matrix:
  exclude:
    # style runs on 2.7 only so that it runs first
    - env: STYLE=1
      python: 3.4
    - env: STYLE=1
      python: 3.5
    - env: STYLE=1
      python: 3.6
services: docker
install: pip install -c travis-constraints.txt tox tox-docker
script:
    - if test -n "$PYMONGO"; then tox -e $(tox -l | grep "^$PYMONGO" | tr "\n" ","); fi
    - if test -n "$STYLE"  ; then tox -e style; fi
