language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
    # keep this list in sync with what's in tox.ini
    - PYMONGO=pymongo30
    - PYMONGO=pymongo31
    - PYMONGO=pymongo32
    - PYMONGO=pymongo33
    - PYMONGO=pymongo34
    - PYMONGO=pymongo35
    - PYMONGO=pymongo36
    - STYLE=1
matrix:
  exclude:
    # style runs on 3.6 only (arbitrary, just need one)
    - env: STYLE=1
      python: 2.7
    - env: STYLE=1
      python: 3.4
    - env: STYLE=1
      python: 3.5
services: docker
install: pip install tox tox-docker
script: tox -e $(tox -l | grep "^$PYMONGO" | tr "\n" ",")
