language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
    # keep this list in sync with what's in tox.ini
    - PYMONGO=pymongo30
    - PYMONGO=pymongo31
    - PYMONGO=pymongo32
    - PYMONGO=pymongo33
    - PYMONGO=pymongo34
    - PYMONGO=pymongo35
    - PYMONGO=pymongo36
services: docker
install: pip install tox tox-docker
script: tox -e $(tox -l | grep "^$PYMONGO" | tr "\n" ",")
