sudo: true
dist: xenial
language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
env:
    # keep this list in sync with what's in tox.ini
    - PYMONGO=pymongo30
    - PYMONGO=pymongo31
    - PYMONGO=pymongo32
    - PYMONGO=pymongo33
    - PYMONGO=pymongo34
    - PYMONGO=pymongo35
    - PYMONGO=pymongo36
    - PYMONGO=pymongo37
matrix:
  include:
    - env: STYLE=1
      python: 2.7
services: docker
install: pip install tox tox-docker
script:
    - if test -n "$PYMONGO"; then tox -e $(tox -l | grep "^$PYMONGO" | tr "\n" ","); fi
    - if test -n "$STYLE"  ; then tox -e style; fi
